#!/bin/bash
PASSED=$@;

if [[ -d $PASSED ]] || [ "$#" -gt 1 ]; then
    tar -c $PASSED | xz -c > "$PASSED.tar.xz"
elif [[ -f $PASSED ]]; then
    xz -c "$PASSED" > "$PASSED.xz"
else
    echo "$PASSED is not valid"
    exit 1
fi


