(deftheme monokai
  "Created 2012-08-22.")

(custom-theme-set-faces
 'monokai
 '(cursor ((t (:foreground "#F92672"))))
 '(hl-line ((t (:background "#141411"))))
 '(minibuffer-prompt ((t (:foreground "#75715E"))))
 '(mode-line ((t (:background "#595959" :foreground "#E6E6E6"))))
 '(region ((t (:background "#383830"))))
 '(show-paren-match-face ((t (:background "#383830"))))
 '(font-lock-builtin-face ((t (:foreground "#A6E22A"))))
 '(font-lock-comment-face ((t (:foreground "#75715E"))))
 '(font-lock-constant-face ((t (:foreground "#AE81FF"))))
 '(font-lock-doc-string-face ((t (:foreground "#E6DB74"))))
 '(font-lock-function-name-face ((t (:foreground "#A6E22A"))))
 '(font-lock-keyword-face ((t (:foreground "#F92672"))))
 '(font-lock-string-face ((t (:foreground "#E6DB74"))))
 '(font-lock-type-face ((t (:foreground "#89BDFF"))))
 '(font-lock-variable-name-face ((t (:foreground "#F92672"))))
 '(font-lock-warning-face ((t (:bold t :foreground "#FD5FF1"))))
 '(cua-rectangle ((t (:background "#141411"))))
 '(ido-first-match ((t (:foreground "#AE81FF"))))
 '(ido-only-match ((t (:foreground "#A6E22A"))))
 '(ido-subdir ((t (:foreground "#89BDFF"))))
 '(whitespace-space ((t (:foreground "#595959"))))
 '(yas/field-highlight-face ((t (:background "#383830"))))
 '(default ((t (:foreground "#F8F8F2" :background "#272822")))))

(provide-theme 'monokai)
